---
title: "Sentiment Analysis"
teaching: 0
exercises: 0
---

:::::::::::::::::::::::::::::::::::::: questions 

- What is sentment analysis?
- How can text analysis evaluate emotion?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Analyze sentiment using general-purpose lexicons
- Visualize the sentiment analysis results using column chart and word cloud 

::::::::::::::::::::::::::::::::::::::::::::::::

## Sentiment Analysis

Sentiment Analysis identifies the emotional tone behind a body of text. Sentiment Analysis or opinion mining is a text analysis technique that automatically identify and extracts the sentiment tone from within text. The analysis utlizes lexicons to help analysize the content of the other texts. The lexicons have already identfied words the emotional tone that then can be compared to in other texts.

The tidytext package comes with three sentiment lexicons in the sentiments dataset. The lexicons are the sentiment lexicon from Bing Liu and collaborators, the NRC Emotion Lexicon from Saif Mohammad and Peter Turney, and the lexicon of Finn Arup Nielsen. These lexicons are based on unigrams, i.e., single words from the English language. The bing lexicon categorizes words into positive or negative, the nrc lexicon categorizes words into emotions anger, sadness, surprise, and joy, and the AFINN lexicon categorizes words using a score, with negative scores indicating a negative sentiment.

The function get_sentiments() allows us to get specific sentiment lexicons with the appropriate measures for each one.














::::::::::::::::::::::::::::::::::::: keypoints 

- Use general purpose lexicons
- Use sentiments 
- Run `sandpaper::check_lesson()` to identify any issues with your lesson
- Run `sandpaper::build_lesson()` to preview your lesson locally

::::::::::::::::::::::::::::::::::::::::::::::::

[r-markdown]: https://rmarkdown.rstudio.com/
